# Generated by Django 3.1.5 on 2021-01-27 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='imgs')),
            ],
        ),
        migrations.CreateModel(
            name='ChangedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(blank=True)),
                ('length', models.IntegerField(blank=True)),
                ('photo', models.ImageField(upload_to='changed_imgs')),
                ('not_changed_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changed', to='compressor.image')),
            ],
        ),
    ]
