# Generated by Django 3.1.5 on 2021-01-19 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('length', models.ImageField(upload_to='')),
                ('photo', models.ImageField(upload_to='changed_imgs')),
                ('not_changed_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changed', to='compressor.image')),
            ],
        ),
    ]
