# Generated by Django 3.1.5 on 2021-01-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0002_changedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changedimage',
            name='length',
            field=models.IntegerField(),
        ),
    ]
