# Generated by Django 3.1.5 on 2021-01-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0003_auto_20210119_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changedimage',
            name='height',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='changedimage',
            name='length',
            field=models.IntegerField(blank=True),
        ),
    ]
