# Generated by Django 3.1.5 on 2021-01-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0004_auto_20210121_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
        migrations.AddField(
            model_name='image',
            name='link',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(blank=True, upload_to='imgs'),
        ),
    ]
