# Generated by Django 3.1.5 on 2021-01-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0005_auto_20210122_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
